apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket-server
  template:
    metadata:
      labels:
        app: websocket-server
    spec:
      containers:
      - name: websocket-server
        image: thalla22/websocket_server_arm
        ports:
        - containerPort: 7890
        readinessProbe:
          tcpSocket:
            port: 7890
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: websocket-server-service
spec:
  selector:
    app: websocket-server
  type: NodePort
  ports:
  - name: websocket
    port: 7890
    targetPort: 7890
    nodePort: 30001
